### YamlMime:FAQ
metadata:
  title: Scentralizowane wdrażanie — często zadawane pytania
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: faq
  ms.service: o365-administration
  ms.localizationpriority: medium
  ms.collection:
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  - Adm_TOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: Zapoznaj się z odpowiedziami na często zadawane pytania dotyczące scentralizowanego wdrażania z Centrum administracyjne platformy Microsoft 365.
  ms.openlocfilehash: 870e59a96f1dee5e56b130f7750faa0addd593c9
  ms.sourcegitcommit: 45bc65972d4007b2aa7760d4457a0d2699f81926
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 04/20/2022
  ms.locfileid: "64971087"
title: Scentralizowane wdrażanie — często zadawane pytania
summary: Wdrożenie scentralizowane to zalecany sposób wdrażania Office 365 administratora Office dodatków (Word, Excel, PowerPoint i Outlook) dla użytkowników i grup w organizacji, pod warunkiem że organizacja spełnia wszystkie wymagania dotyczące korzystania ze scentralizowanego wdrożenia zgodnie z opisem w tym artykule.
sections:
- name: Zignorowano
  questions:
  - question: >
      Jak mogę wiedzieć, czy moja organizacja została skonfigurowana na potrzeby wdrożenia scentralizowanego?
    answer: "Scentralizowane wdrażanie dodatków wymaga, aby użytkownicy korzystali z Aplikacje Microsoft 365 dla przedsiębiorstw (i logowali się do Office przy użyciu poświadczeń logowania organizacyjnego) i mieli Exchange Online skrzynki pocztowe. Katalog subskrypcji musi znajdować się w Azure Active Directory lub w katalogu federacyjnym. \n \nScentralizowane wdrażanie jest obsługiwane tylko w przypadku skrzynek pocztowych online. Nie obsługuje wdrażania w lokalnych Exchange skrzynkach pocztowych.\n\nMożesz użyć [narzędzia do sprawdzania zgodności scentralizowanego wdrożenia](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) , aby określić, czy twoja subskrypcja kwalifikuje się. \n  \n"
  - question: >
      Jak kierować przydziały użytkowników dodatków za pomocą scentralizowanego wdrożenia?
    answer: "Wdrożenie scentralizowane obsługuje przypisania do poszczególnych użytkowników, grup i wszystkich osób w dzierżawie. Scentralizowane wdrożenie może być używane dla użytkowników w grupach lub grupach najwyższego poziomu bez grup nadrzędnych, ale nie dla użytkowników w grupach zagnieżdżonych lub grupach, które mają grupy nadrzędne. Scentralizowane wdrożenie jest również częścią większości grup Azure Active Directory, w tym grup Office 365, list dystrybucyjnych i grup zabezpieczeń. \n\nLepiej jest używać przypisań grup zamiast przypisania poszczególnych użytkowników w celu łatwiejszego zarządzania.\n \nAby uzyskać więcej informacji, zobacz [Przypisywanie użytkowników i grup](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: >
      Jak długo trwa wyświetlanie dodatków dla wszystkich użytkowników?
    answer: >
      Wyświetlenie nowego wdrożenia dodatku dla wszystkich użytkowników może potrwać do 24 godzin. Może upłynąć do 72 godzin w przypadku aktualizacji dodatków, zmian po włączeniu lub wyłączeniu lub usunięcia dodatków w celu odzwierciedlenia ich dla użytkowników.
  - question: >
      Jak zarządzać dostępem użytkowników do dodatków dla mojej organizacji jako administrator?
    answer: >
      Aby ułatwić wdrażanie dodatków dla użytkowników, grup lub całej organizacji, zalecamy, aby administratorzy korzystali ze scentralizowanego wdrożenia.


      Aby uzyskać więcej informacji na temat zarządzania dostępem użytkowników, zobacz:
       - [Zapobiegaj pobieraniu dodatków, wyłączając magazyn Office dla wszystkich klientów (z wyjątkiem Outlook)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Określ administratorów i użytkowników, którzy mogą instalować dodatki i zarządzać nimi dla Outlook](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "Czy wdrożenie scentralizowane zapewni administratorom elastyczność wyboru metody wdrażania dla Outlook dodatków? \n"
    answer: "Tak. Scentralizowane wdrożenie zapewnia administratorom elastyczność wyboru jednej z dwóch metod wdrażania dla dodatków Outlook podczas wdrażania dodatków:\n         \n**Dostępne** Użytkownicy mogą zainstalować dodatek Outlook, wybierając pozycję **Strona główna > Uzyskaj więcej dodatków > zarządzanych przez administratora**.\n \n**Opcjonalne** Dodatek jest wdrażany automatycznie dla przypisanych użytkowników, ale mogą je usunąć.\n    \n"
  - question: "Czy administratorzy mogą aktualizować dodatki biznesowe(LOB)? \n"
    answer: "Tak. Administratorzy mogą przekazać nowy plik manifestu w celu obsługi zmian metadanych dla dodatków lob wdrożonych przez administratora. Dodatek zostanie zaktualizowany przy następnym uruchomieniu aplikacji Office. Aplikacja internetowa może się zmienić w dowolnym momencie.\n \nAby uzyskać więcej informacji, zobacz [dodatek biznesowy](./manage-addins-in-the-admin-center.md).  \n"
  - question: "Czy administratorzy mogą wyłączyć dodatki? \n"
    answer: >
      Tak. Administratorzy mogą włączać lub wyłączać wdrażane dodatki dla wszystkich użytkowników z centrum administracyjnego firmy Microsoft.


      Aby uzyskać więcej informacji, zobacz [Stany dodatków](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      Czy administratorzy mogą usuwać lub usuwać dodatki?
    answer: "Tak. Administratorzy mogą usuwać dodatki wdrożone dla wszystkich użytkowników z centrum administracyjnego firmy Microsoft.\n\nAby uzyskać więcej informacji, zobacz [Usuwanie dodatku](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "Czy administratorzy mogą wdrażać płatne dodatki ze sklepu Office Przy użyciu scentralizowanego wdrożenia? \n"
    answer: "L.p. Obecnie nie można wdrożyć płatnych dodatków ze sklepu Office Store przy użyciu wdrożenia scentralizowanego. \n \nZalecamy skontaktowanie się z deweloperem niezależnego dostawcy oprogramowania w celu utworzenia płatnego dodatku w celu zażądania pliku manifestu lub adresu URL. Administrator dzierżawy może następnie wdrożyć dodatek jako dodatek lob przy użyciu scentralizowanego wdrożenia.\n   \n"
  - question: "Której roli administratora potrzebuję do zarządzania dodatkami dla mojej organizacji? \n"
    answer: "Administrator globalny to zalecana rola z pełnym dostępem do cyklu życia zarządzania dodatkami. Jeśli jesteś osobą, która kupiła subskrypcję Microsoft 365 Business, jesteś administratorem globalnym.\n\nTwoja subskrypcja zawiera zestaw ról administratora, które można przypisać innym użytkownikom w organizacji. Każda rola administratora jest mapowana na typowe funkcje biznesowe i daje osobom w organizacji uprawnienia do wykonywania określonych zadań w Centrum administracyjne platformy Microsoft 365.  \n \nAby uzyskać więcej informacji, zobacz [Przypisywanie ról administratora](../add-users/assign-admin-roles.md?view=o365-worldwide)."
